name: Trigger a process in Control Room

on:
  pull_request:
    branches:
      - main

jobs:
  run-process:
    runs-on: ubuntu-latest
    name: Trigger process
    steps:
      - name: Trigger Control Room process run
        uses: robocorp/action-trigger-process@v1
        with:
          api-key: ${{ secrets.ROBOCORP_API_KEY }}
          workspace-id: ${{ secrets.ROBOCORP_WORKSPACE_ID }}
          process-id: ${{ secrets.ROBOCORP_PROCESS_ID }}
          payload: '{"search_phrase": "computer science", "news_category": "Arts", "num_months": 0}'
          await-complete: true