name: Upload to Robocorp Control Room

on: [push]

jobs:
  upload-robot:
    runs-on: ubuntu-latest
    name: Upload robot
    steps:
      - name: Checkout files from repository
        uses: actions/checkout@v2
      - name: Upload robot to Control Room
        uses: robocorp/action-upload-robot@v1
        with:
          workspace-key: ${{ secrets.ROBOCORP_API_KEY }}
          workspace-id: ${{ secrets.ROBOCORP_WORKSPACE_ID }}
          robot-id: ${{ secrets.ROBOCORP_ROBOT_ID }}