name: Upload to Robocorp Control Room

on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Upload to Robocorp Control Room
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Upload Robot to Control Room
        uses: ./
        with:
          workspace-key: ${{ secrets.ROBOCORP_API_KEY }}
          workspace-id: ${{ secrets.ROBOCORP_WORKSPACE_ID }}
          robot-id: ${{ secrets.ROBOCORP_ROBOT_ID }}