name: Upload to Robocorp Control Room

on:
  push:
    branches:
      - master

jobs:
  upload-to-control-room:
    runs-on: ubuntu-latest 
    name: Upload to Control Room

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2 
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
      - name: Login to Robocorp Cloud
        env:
          ROBOCORP_API_KEY: ${{ secrets.ROBOCORP_API_KEY }}
        run: |
          rcc configure credentials ${ROBOCORP_API_KEY}

      - name: Upload Robot to Control Room
        env:
          ROBOCORP_WORKSPACE_ID: ${{ secrets.ROBOCORP_WORKSPACE_ID }}
          ROBOCORP_ROBOT_ID: ${{ secrets.ROBOCORP_ROBOT_ID }}
        run: |
          rcc cloud push -w ${ROBOCORP_WORKSPACE_ID} -r ${ROBOCORP_ROBOT_ID}
